services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - docker-sweetr-db:/var/lib/postgresql/data
      - ./init-app-db.sh:/docker-entrypoint-initdb.d/init-app-db.sh
  dragonfly:
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    ulimits:
      memlock: -1
    command: ["--cluster_mode=emulated", "--lock_on_hashtags"]
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
volumes:
  docker-sweetr-db:
  dragonflydata:
